/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package laboratorium.uruun;

public interface Car {
    boolean needsFuel();
    double getEngineTemperature();
    void driveTo(String destination);
}